name: Deploy World
env: ${{ secrets }}

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

# pm2 start npm --name "world1-maintenance" -- run maintenance
# pm2 start npm --name "world1-server" --kill-timeout 600000 -- run quickstart

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment}}

    steps:
    - name: Download Packed Data
      uses: actions/download-artifact@v4
      with:
        name: packed

    - name: Shutdown World
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          source ~/.bashrc
          cd ${{ secrets.DIR }}
          git pull
          npm i
          pm2 stop ${{ inputs.environment}}-server
          pm2 start ${{ inputs.environment}}-maintenance

    - name: Update Content
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        source: "client,server"
        target: ${{ secrets.DIR }}/data/pack
        rm: true

    - name: Start World
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          pm2 stop ${{ inputs.environment}}-maintenance
          pm2 start ${{ inputs.environment}}-server
